imageTag: multiarch

resources:
  requests: {}

tolerations:
  - key: "app"
    operator: "Equal"
    value: "minecraft"
    effect: "NoSchedule"

livenessProbe:
  initialDelaySeconds: 120
  periodSeconds: 60

readinessProbe:
  initialDelaySeconds: 120
  periodSeconds: 60

minecraftServer:
  eula: "TRUE"

  # One of: LATEST, SNAPSHOT, or a specific version (ie: "1.7.9").
  version: "LATEST"
  # This can be one of "VANILLA", "FORGE", "SPIGOT", "BUKKIT", "PAPER", "FTB", "SPONGEVANILLA"
  type: "PAPER"
  
  viewDistance: 7

  motd: "Welcome to Minecraft on Kubernetes on Rapsberry Pi!"

  memory: 512M

persistence:
  ## minecraft data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # storageClass: "-"
  dataDir:
    enabled: true
    Size: 10Gi
